### ISSUE TITLE
Tag must be a valid java class name

### ISSUE THREAD

**Issue by dark-chocolate** [myinnos/AppIconNameChanger#5]
error: attribute 'android:name' in  tag must be a valid Java class name

![image](https://user-images.githubusercontent.com/40364434/41547718-9c30d06c-733e-11e8-93fb-33e5b87f1f4f.png)

**Comment by NoorMM786** [comment]
> error: attribute 'android:name' in  tag must be a valid Java class name
> 
> 
> ![image](https://user-images.githubusercontent.com/40364434/41547718-9c30d06c-733e-11e8-93fb-33e5b87f1f4f.png)
> 

How to solve

**Comment by qq273681448** [comment]
HI!我是邵磊，您的邮件我已经收到啦，我会在第一时间给您回复哦。
