### ISSUE TITLE
Can you run it in Android Studio 3.1.3?

### ISSUE THREAD

**Issue by hendrawd** [myinnos/AppIconNameChanger#6]
AAPT2 will show error:
```
error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name.
Message{kind=ERROR, text=error: attribute 'android:name' in <activity-alias> tag must be a valid Java class name., sources=[/Users/hendrawd/AndroidStudioProjects/MyProject/app/build/intermediates/manifests/full/prod/debug/AndroidManifest.xml:59], original message=, tool name=Optional.of(AAPT)}
```

After change `-` to `_`, `MainActivity` is invisible(no launcher at all), so I can't run the app.

**Comment by as-if-iam** [comment]
Working here buddy :-) 

I had same issue then I saw that my package name is activity and then I added the class launcher name 

activity.SplashActivity-one
activity.SplashActivity-two
activity.SplashActivity-three

and it worked

**Comment by as-if-iam** [comment]
and write this in gradle.properties

android.enableAapt2=false

**Comment by hendrawd** [comment]
After learning about the downside of this method(in some devices, the icons will never show up at all), we decided to drop this feature, so I think I will not try this @asif84468 . Disabling aapt2 also will make our app build slower and not optimize for release apk. I will wait for @myinnos to fix it and not gona create a pull request to fix it.

**Comment by myinnos** [comment]
@hendrawd @asif84468  fixed in new version please update lib gradel version [Read.Me](https://github.com/myinnos/AppIconNameChanger/blob/master/README.md)
