### ISSUE TITLE
Error type 3 while re-installing app

### ISSUE THREAD

**Issue by Mateeen** [myinnos/AppIconNameChanger#7]
we used this library and it works great.
the issue is when we successfully change the app icon to settings icon then try to re-install app using android studio it gives an error below.
Error while executing: am start -n "in.myinnos.changeappiconandname/in.myinnos.changeappiconandname.MainActivity-settings" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=in.myinnos.changeappiconandname/.MainActivity-settings }
Error type 3
Error: Activity class {in.myinnos.changeappiconandname/in.myinnos.changeappiconandname.MainActivity-settings} does not exist.

Error while Launching activity

**Comment by shafayatrmg** [comment]
I am having the same issue as well. Did you find any solution? I think it will be risky to use this library in production environment.

**Comment by ercandemirtekin** [comment]
Could you find any solutions or any other way for changing app icon ?

**Comment by eduardo-calzado-ag** [comment]
+1

**Comment by sureshperiyasamy** [comment]
+1

**Comment by myinnos** [comment]
@Mateeen @shafayatrmg @ercandemirtekin @eduardo-calzado-agentero @sureshperiyasamy  fixed in new version please update lib gradel version [Read.Me](https://github.com/myinnos/AppIconNameChanger/blob/master/README.md)
