### ISSUE TITLE
Installation error reporting

### ISSUE THREAD

**Issue by lnl1314abm** [myinnos/AppIconNameChanger#9]
Error while executing: am start -n "in.myinnos.changeappiconandname/in.myinnos.changeappiconandname.MainActivity-settings" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=in.myinnos.changeappiconandname/.MainActivity-settings }
Error type 3
Error: Activity class {in.myinnos.changeappiconandname/in.myinnos.changeappiconandname.MainActivity-settings} does not exist.

Error while Launching activity

**Comment by sureshperiyasamy** [comment]
@myinnos Any solution regarding this

**Comment by myinnos** [comment]
@sureshperiyasamy fixed in new version please update lib gradel version [Read.Me](https://github.com/myinnos/AppIconNameChanger/blob/master/README.md)
